# Generated by Django 5.0.1 on 2024-01-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carstoid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_to_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='carstoid.cartoid')),
            ],
        ),
    ]
