# Generated by Django 5.0.1 on 2024-01-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='car_to_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default='Car', max_length=500),
            preserve_default=False,
        ),
    ]
