# Generated by Django 5.0.1 on 2024-01-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstoid', '0003_cartoid_comment'),
        ('comments', '0003_remove_comment_car_to_id_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoid',
            name='comment',
        ),
        migrations.AddField(
            model_name='cartoid',
            name='identified_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_to_id_commented_on', to='comments.comment'),
        ),
    ]
